site_name: PromptX AI
site_author: PromptX AI
site_description: >-
  AI Consulting, RAG, and other personal notes.
# Repository configuration - this will display current stars and forks from GitHub
repo_name: localGPT
repo_url: https://github.com/PromtEngineer/localGPT
site_url: https://jxnl.co/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 PromptX AI

# Social links and additional site configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PromtEngineer/localGPT
      name: localGPT on GitHub
theme:
  name: material
  custom_dir: overrides
  # Enable GitHub statistics (stars and forks)
  features:
    - content.action.edit
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - navigation.top
    - header.autohide
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  # Enable real-time repository information (stars, forks)
    theme:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
      - scheme: youtube
  font:
    text: Roboto
    code: Roboto Mono
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: jxnl 
      repo: instructor
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
nav:
  - Home: 
    - About Me: 'index.md'
    - Services: 'services.md'
  - Consulting:
    - Consulting Services: "services.md"
    - Book a Consultation: "book-a-call.md"
  - RAG Course: "rag-beyond-basics.md"
  - YouTube Videos: "youtube.md"
  - Writing:
    - "writing/index.md"
plugins:
  - social
  - rss:
      match_path: "writing/posts/.*"
      skip_ci_warning: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
  - blog:
      enabled: !ENV CI
      blog_dir: writing
      blog_toc: true
      post_dir: writing/posts
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"
extra:
  analytics:
    provider: google
    property: G-686PKP2V2V
  css:
    - stylesheets/extra.css
    - stylesheets/mermaid.css
  javascript:
    - javascripts/mermaid-zoom.js
  social:
    - icon: fontawesome/solid/rss
      link: feed_rss_created.xml
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/engineerrprompt
    - icon: fontawesome/brands/github
      link: https://github.com/PromtEngineer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/engineerprompt
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@engineerprompt
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/analytics.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2025 PromptX AI
