authors:
  muhammad:
    name: Muhammad Farooq
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/134474669?v=4
    url: https://twitter.com/intent/follow?screen_name=jxnlco
  